[project]
name = "qaaas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["pydantic>=2.9.1", "qiskit>=1.0.0"]

[tool.hatch.build.targets.wheel]
packages = ["qaaas"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
